
package telas;

import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.Scanner;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

import historia.Capitulo;
import historia.Escolhas;
import script.ControleBotoeSelecionados;
import script.Escritor;
import script.CarregadorDoTexto;

/**
 *
 * @author JYrik
 */
public class TelaPricipal extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form TelaPricipal
     */

    private static final long serialVersionUID = 1L;

    public ControleBotoeSelecionados controle;

    private String textoLido;
    public java.awt.event.ActionEvent evt;

    public String getTextoLido() {
        return textoLido;
    }

    public void setTextoLido(String textoLido) {
        this.textoLido = textoLido;
    }

    public TelaPricipal() {
        super("MagicBoook");
        // this.textoLido= "";
        initComponents();

        // btscam = new Scanner(enviar.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        enviar = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        JComboBox<String> jComboBox1 = new javax.swing.JComboBox<String>();
        jPanel4 = new javax.swing.JPanel();
        energiaBar1 = new javax.swing.JLabel();
        vidaBar1 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        energia1 = new javax.swing.JLabel();
        nome3 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        energia3 = new javax.swing.JLabel();
        energiaBar3 = new javax.swing.JLabel();
        vidaBar3 = new javax.swing.JLabel();
        nome4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(1, 3, 42));

        jPanel1.setBackground(new java.awt.Color(50, 46, 46));

        texto.setBackground(new java.awt.Color(242, 235, 235));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        texto.setLineWrap(true);
        texto.setRows(5);
        texto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(texto);

        enviar.setBackground(new java.awt.Color(122, 250, 26));
        enviar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        enviar.setForeground(new java.awt.Color(255, 255, 255));
        enviar.setText("ENVIAR");
        enviar.setMultiClickThreshhold(1L);
        enviar.setName(""); // NOI18N
        enviar.setSelected(true);
        enviar.setAlignmentX(CENTER_ALIGNMENT);
        enviar.setAlignmentY(CENTER_ALIGNMENT);
        enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMouseClicked(evt);
            }
        });
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        enviar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                enviarPropertyChange(evt);
            }
        });

        reiniciar.setBackground(new java.awt.Color(0, 102, 102));
        reiniciar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        reiniciar.setText("REINICIAR");
        reiniciar.setBounds(300, 100, 30, 10);
        // jPanel4.add(enviar);
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }

            private void reiniciarActionPerformed(ActionEvent evt) {
                Escritor escreve = new Escritor();
                Capitulo c = Capitulo.getCb().getCapitulo();
                try {
                    escreve.escreverCapitulo("rsc\\JsonFiles\\loads\\loadCapitulo.json", c);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        //
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                // .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                // 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 162,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(reiniciar)
                                                .addGap(63, 63, 63))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(62, Short.MAX_VALUE)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                // .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                // javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(39, 39, 39)))));

        jPanel4.setBackground(new java.awt.Color(1, 3, 42));

        energiaBar1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        energiaBar1.setForeground(new java.awt.Color(255, 0, 0));

        vidaBar1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        vidaBar1.setForeground(new java.awt.Color(255, 255, 0));

        vida1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        vida1.setForeground(new java.awt.Color(255, 255, 255));
        vida1.setText("VIDA");

        energia1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        energia1.setForeground(new java.awt.Color(255, 255, 255));
        energia1.setText("ENERGIA");

        nome3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nome3.setForeground(new java.awt.Color(255, 255, 204));
        nome3.setText("");

        vida3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        vida3.setForeground(new java.awt.Color(255, 255, 255));
        vida3.setText("VIDA");

        energia3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        energia3.setForeground(new java.awt.Color(255, 255, 255));
        energia3.setText("ENERGIA");

        energiaBar3.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        energiaBar3.setForeground(new java.awt.Color(255, 255, 255));

        vidaBar3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        vidaBar3.setForeground(new java.awt.Color(255, 255, 255));

        nome4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nome4.setForeground(new java.awt.Color(255, 255, 204));
        nome4.setText("VOCÊ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(vida3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(energia3))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(energiaBar3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                286,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addGap(55, 55, 55)
                                                                                .addGroup(jPanel4Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(nome4)
                                                                                        .addComponent(vidaBar3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)))))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(145, 145, 145)
                                                .addComponent(nome3)))
                                .addGap(0, 16, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(energia1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vidaBar1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(energiaBar1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(nome3, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(energiaBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(energia1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vidaBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11,
                                        Short.MAX_VALUE)
                                .addComponent(nome4, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vidaBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(energia3, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(energiaBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(355, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 10, Short.MAX_VALUE)));
        // j//ComboBox1.addItem("oi");
        // jComboBox1.addItem("o11i");
        // jComboBox1.removeAllItems();
        // enviar.setBounds(1, 660,500, 100);
        // jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 24));
        // System.out.println(jComboBox1);
        // jPanel4.add(enviar);
        

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_enviarMouseClicked

    }// GEN-LAST:event_enviarMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void enviarPropertyChange(java.beans.PropertyChangeEvent evt) {
    }

    public void enviarActionPerformed(java.awt.event.ActionEvent evt) {

        // como fazer que seja criado aq o combox/ botões ???

        Capitulo.getCb().getCapitulo().acaoEscolher(Capitulo.getCb().getCapitulo());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("construindo tela");
                TelaPricipal tela = new TelaPricipal();
                tela.setVisible(true);
                System.out.println("construindo script");
                try {
                    CarregadorDoTexto script = new CarregadorDoTexto(tela);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel energia1;
    private javax.swing.JLabel energia3;
    private javax.swing.JLabel energiaBar1;
    private javax.swing.JLabel energiaBar3;
    private javax.swing.JButton enviar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome3;
    private javax.swing.JLabel nome4;
    private javax.swing.JButton reiniciar;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida3;
    private javax.swing.JLabel vidaBar1;
    private javax.swing.JLabel vidaBar3;

    // End of variables declaration//GEN-END:variables
    public javax.swing.JLabel getEnergia1() {
        return energia1;
    }

    public void setEnergia1(javax.swing.JLabel energia1) {
        this.energia1 = energia1;
    }

    public javax.swing.JLabel getEnergia3() {
        return energia3;
    }

    public void setEnergia3(javax.swing.JLabel energia3) {
        this.energia3 = energia3;
    }

    public javax.swing.JLabel getEnergiaBar1() {
        return energiaBar1;
    }

    public void setEnergiaBar1(javax.swing.JLabel energiaBar1) {
        this.energiaBar1 = energiaBar1;
    }

    public javax.swing.JLabel getEnergiaBar3() {
        return energiaBar3;
    }

    public void setEnergiaBar3(javax.swing.JLabel energiaBar3) {
        this.energiaBar3 = energiaBar3;
    }

    public javax.swing.JButton getEnviar() {
        return enviar;
    }

    public void setEnviar(javax.swing.JButton enviar) {
        this.enviar = enviar;
    }

    public javax.swing.JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(javax.swing.JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JLabel getNome3() {
        return nome3;
    }

    public void setNome3(javax.swing.JLabel nome3) {
        this.nome3 = nome3;
    }

    public javax.swing.JLabel getNome4() {
        return nome4;
    }

    public void setNome4(javax.swing.JLabel nome4) {
        this.nome4 = nome4;
    }

    public javax.swing.JButton getReiniciar() {
        return reiniciar;
    }

    public void setReiniciar(javax.swing.JButton reiniciar) {
        this.reiniciar = reiniciar;
    }

    public javax.swing.JTextArea getTexto() {
        return texto;
    }

    public void setTexto(javax.swing.JTextArea texto) {
        this.texto = texto;
    }

    public javax.swing.JLabel getVida1() {
        return vida1;
    }

    public void setVida1(javax.swing.JLabel vida1) {
        this.vida1 = vida1;
    }

    public javax.swing.JLabel getVida3() {
        return vida3;
    }

    public void setVida3(javax.swing.JLabel vida3) {
        this.vida3 = vida3;
    }

    public javax.swing.JLabel getVidaBar1() {
        return vidaBar1;
    }

    public void setVidaBar1(javax.swing.JLabel vidaBar1) {
        this.vidaBar1 = vidaBar1;
    }

    public javax.swing.JLabel getVidaBar3() {
        return vidaBar3;
    }

    public void setVidaBar3(javax.swing.JLabel vidaBar3) {
        this.vidaBar3 = vidaBar3;
    }
    
    

}
