
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JYrik
 */

    

public class Livro extends javax.swing.JFrame {
   
    /**
     * Creates new form NewJFrame
     */
    public String lido ="";
    int contagem = 0;
   
    
    class B1{
        int estado = 1;
        String entrada;

        public String getEntrada() {
            return entrada;
        }

        public void setEntrada(String entrada) {
            this.entrada = entrada;
        }
        

        public int getEstado() {
            return estado;
        }

        public void setEstado(int estado) {
            this.estado = estado;
        }
        
    }
    public B1 btsim = new B1();
    public B1 btnao = new B1();
    public B1 btenviar = new B1();
    public B1 btrep = new B1();
    
    public Livro() throws InterruptedException {
         initComponents();
            inicio();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sim = new javax.swing.JButton();
        nao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        ler = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        responder = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 46, 46));

        sim.setBackground(new java.awt.Color(51, 204, 0));
        sim.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        sim.setForeground(new java.awt.Color(255, 255, 255));
        sim.setText("SIM");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });

        nao.setBackground(new java.awt.Color(255, 0, 51));
        nao.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        nao.setForeground(new java.awt.Color(255, 255, 255));
        nao.setText("NÃO");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });

        texto.setBackground(new java.awt.Color(242, 235, 235));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        texto.setLineWrap(true);
        texto.setRows(5);
        texto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(texto);

        ler.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        ler.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ler.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lerActionPerformed(evt);
            }
        });

        enviar.setBackground(new java.awt.Color(0, 0, 153));
        enviar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        enviar.setForeground(new java.awt.Color(255, 255, 255));
        enviar.setText("ENVIAR");
        enviar.setSelected(true);
        enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMouseClicked(evt);
            }
        });
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        enviar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                enviarPropertyChange(evt);
            }
        });

        responder.setBackground(new java.awt.Color(255, 124, 26));
        responder.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        responder.setForeground(new java.awt.Color(255, 255, 255));
        responder.setText("RESPONDER");
        responder.setSelected(true);
        responder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                responderMouseClicked(evt);
            }
        });
        responder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderActionPerformed(evt);
            }
        });
        responder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                responderPropertyChange(evt);
            }
        });

        reiniciar.setBackground(new java.awt.Color(0, 102, 102));
        reiniciar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        reiniciar.setText("REINICIAR");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(responder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sim, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reiniciar)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ler, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(enviar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(responder)
                            .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sim, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
         btenviar.setEstado(btenviar.getEstado()+1);
         btenviar.setEntrada(lendo());     
    }//GEN-LAST:event_enviarActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        // TODO add your handling code here:
        int estado = btsim.getEstado();
        btsim.setEstado(estado+1);
        
        
        if(estado == 1){
            contagem +=5;
            texto.append("""
                         
                         ---------------------------------------------
                         Você acabou de acordar um pouco sonolento vai 
                         para o banheiro escovar os dentes , você repara em algo
                         esquisito na mesa de jantar .
                         
                         Você olha para fora do quarto e vê um livro estranho 
                         você vai pegar o livro ?""");
            
           
        texto.append("╔══╗ \n" +
"║██║ \n" +
"║(O)║♫ ♪ ♫ ♪\n" +
"╚══╝\n" +
"▄ █ ▄ █ ▄ ▄ █ ▄ █ ▄ █\n" +
"Min- - - - - - - - - - - -●Max\n");
        

        }
        if(estado == 2){
            int estadoTexto = btenviar.getEstado();
            texto.append("""
                         
                         
                         ..............................................
                     https://i.ytimg.com/vi/xB_O0Adpm80/maxresdefault.jpg
                         ...............................................
                         Você toca no livro e no mesmo instante 
                         
                     o livro se abre no país em que as pessoas viraram pedras
                               por causa de um vulcão. Qual o país ? Pergunta um 
                        homem em pé de frente a janela .
                         Você responde que é na 
                         .....
                         
                               """);
            
               
          
      
           
               
           
            
        }
        
        
    }//GEN-LAST:event_simActionPerformed

    private void enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarMouseClicked

    private void enviarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_enviarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarPropertyChange

    private void responderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_responderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_responderMouseClicked

    private void responderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderActionPerformed
        // TODO add your handling code here:
          int estado = btrep.getEstado();
        btrep.setEstado(estado+1);
        
         if(lido.equals("itália")){
             contagem +=5;
                finais(contagem);
           }
         if(lido.equals("sócrates")){
             contagem+= 2;
             finais(contagem);
         }
         if(estado == 1){
            if (!lido.equals("sócrates") || !lido.equals("itália")){
             
             contagem+=1;
             finais(contagem);
            }
         }
    }//GEN-LAST:event_responderActionPerformed

    private void responderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_responderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_responderPropertyChange

    private void lerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lerActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        // TODO add your handling code here:
        int estado = btsim.getEstado();
        btsim.setEstado(estado+1);
        if(estado == 1){
            texto.append("""
                         
                         .............................................
                         Você escuta barulhos muito altos dentro da sua própria 
                         mente , você começa a ver algumas imagens em delírio!!
                         
                         César algusto o imperador precisa de UMA casa ,
                         você ficou preso num sono profundo , 
                         
                         decifre a senha pra despertar !
                         
                         DICA: Tó tfj rvf obeb tfj ! Tpv p bvups !
                         """);
        }
        if(estado == 2){
            contagem+=3;
            finais(contagem);
        }
    }//GEN-LAST:event_naoActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        btenviar.setEstado(1);
        btrep.setEstado(1);
        btnao.setEstado(1);
        btsim.setEstado(1);
        contagem = 0;
        texto.setText("");
        inicio();
       
    }//GEN-LAST:event_reiniciarActionPerformed
    public String lendo(){
       
        lido = ler.getText().toLowerCase();
        System.out.println(lido);
        ler.setText("");
        
        return lido;
        
    }
    public void finais (int pontos){
        if(pontos == 1){
            texto.append("¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶11111111111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶1111111111111111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶1111111¶¶¶¶¶¶¶¶111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶11111111¶¶¶111¶¶¶¶¶¶¶1111111¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶1111111111¶¶¶1111111111111111111¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶111111111111¶¶¶¶1111111111¶¶¶¶¶¶1¶¶¶¶¶1¶¶¶\n" +
"¶¶111111111111111111111111111¶¶111111111111¶¶\n" +
"¶¶111111111111111111111111111111111111111111¶\n" +
"¶1111¶¶¶¶1111111111111111111111111111111111¶¶\n" +
"¶11¶¶¶¶¶111111111111111111111111111¶¶¶¶¶¶11¶¶\n" +
"¶1¶¶¶¶¶111111111111111111111111111¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶11111111111¶11111111111111¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶111111111111¶¶1111111111111¶¶¶¶¶¶¶¶1¶¶¶\n" +
"¶¶¶¶¶¶1111111111111¶¶¶111111111111¶¶¶¶¶11¶¶¶¶\n" +
"¶¶¶¶¶¶1111111¶¶¶11111¶¶¶¶111111111111111¶¶¶¶¶\n" +
"¶¶¶¶¶¶11111¶¶¶¶¶11111111¶¶¶¶¶¶¶¶¶¶¶¶111¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶111¶¶¶¶¶¶¶11111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶¶11111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n"
                    + "VOCÊ ESTÁ SONHANDO ?!!");
        }
        if(pontos == 2){
            texto.append("\n_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n" +
"_¶¶___________________________________¶¶\n" +
"_¶¶___________________________________¶¶\n" +
"__¶¶_________________________________¶¶_\n" +
"__¶¶_________________________________¶¶_\n" +
"___¶¶_______________________________¶¶__\n" +
"___¶¶______________________________¶¶___\n" +
"____¶¶¶__________________________¶¶¶____\n" +
"_____¶¶¶¶_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶¶¶_____\n" +
"_______¶¶¶¶_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶¶¶_______\n" +
"_________¶¶¶¶_¶¶¶¶¶¶¶¶¶¶¶¶_¶¶¶¶_________\n" +
"___________¶¶¶¶¶_¶¶¶¶¶¶¶_¶¶¶¶___________\n" +
"______________¶¶¶¶_¶¶¶_¶¶¶______________\n" +
"________________¶¶¶_¶_¶¶________________\n" +
"_________________¶¶¶_¶¶_________________\n" +
"__________________¶¶_¶¶_________________\n" +
"__________________¶¶_¶__________________\n" +
"__________________¶¶_¶¶_________________\n" +
"________________¶¶¶_¶_¶¶¶_______________\n" +
"_____________¶¶¶¶¶__¶__¶¶¶¶¶____________\n" +
"__________¶¶¶¶¶_____¶_____¶¶¶¶__________\n" +
"________¶¶¶¶________¶_______¶¶¶¶¶_______\n" +
"_______¶¶¶__________¶__________¶¶¶¶_____\n" +
"_____¶¶¶____________¶____________¶¶¶____\n" +
"____¶¶¶_____________¶______________¶¶___\n" +
"___¶¶¶______________¶_______________¶¶__\n" +
"___¶¶_______________¶________________¶¶_\n" +
"__¶¶________________¶________________¶¶_\n" +
"__¶¶_______________¶¶¶________________¶_\n" +
"__¶¶_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶\n" +
"__¶¶_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶\n" +
"__¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶\n");
            texto.append("""
                         VOCÊ GANHOU O PODER DE VIAJAR NO TEMPO E ENTRE REINOS
                         AGORA VOCÊ É UM VIAJANTE DO TEMPO !!
                         """);
        }
        if(pontos == 8){
            
            texto.append("\n─────▄██▀▀▀▀▀▀▀▀▀▀▀▀▀██▄─────\n" +
"────███───────────────███────\n" +
"───███─────────────────███───\n" +
"──███───▄▀▀▄─────▄▀▀▄───███──\n" +
"─████─▄▀────▀▄─▄▀────▀▄─████─\n" +
"─████──▄████─────████▄──█████\n" +
"█████─██▓▓▓██───██▓▓▓██─█████\n" +
"█████─██▓█▓██───██▓█▓██─█████\n" +
"█████─██▓▓▓█▀─▄─▀█▓▓▓██─█████\n" +
"████▀──▀▀▀▀▀─▄█▄─▀▀▀▀▀──▀████\n" +
"███─▄▀▀▀▄────███────▄▀▀▀▄─███\n" +
"███──▄▀▄─█──█████──█─▄▀▄──███\n" +
"███─█──█─█──█████──█─█──█─███\n" +
"███─█─▀──█─▄█████▄─█──▀─█─███\n" +
"███▄─▀▀▀▀──█─▀█▀─█──▀▀▀▀─▄███\n" +
"████─────────────────────████\n" +
"─███───▀█████████████▀───████\n" +
"─███───────█─────█───────████\n" +
"─████─────█───────█─────█████\n" +
"───███▄──█────█────█──▄█████─\n" +
"─────▀█████▄▄███▄▄█████▀─────\n" +
"──────────█▄─────▄█──────────\n" +
"──────────▄█─────█▄──────────\n" +
"───────▄████─────████▄───────\n" +
"─────▄███████───███████▄─────\n" +
"───▄█████████████████████▄───\n" +
"─▄███▀───███████████───▀███▄─\n" +
"███▀─────███████████─────▀███\n" +
"▌▌▌▌▒▒───███████████───▒▒▐▐▐▐\n" +
"─────▒▒──███████████──▒▒─────\n" +
"──────▒▒─███████████─▒▒──────\n" +
"───────▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒───────\n" +
"─────────████░░█████─────────\n" +
"────────█████░░██████────────\n" +
"──────███████░░███████───────\n" +
"─────█████──█░░█──█████──────\n" +
"─────█████──████──█████──────\n" +
"──────████──████──████───────\n" +
"──────████──████──████───────\n" +
"──────████───██───████───────\n" +
"──────████───██───████───────\n" +
"──────████──████──████───────\n" +
"─██────██───████───██─────██─\n" +
"─██───████──████──████────██─\n" +
"─███████████████████████████─\n" +
"─██─────────████──────────██─\n" +
"─██─────────████──────────██─\n" +
"────────────████─────────────\n" +
"─────────────██──────────────\n");
            texto.append("""
                         VOCÊ FOI CAPTURADO PELOS PALHAÇÕS DE VEMPTA 
                         E ACABOU EM UM PESADELO ETERNO !!
                         """);
            
        }
        if(pontos == 6){
            texto.append("n11111111¶111111111111111111111111111111111111 \n" +
"11111111¶¶¶1111111111111111111111111111111111 \n" +
"111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶111111111111111111 \n" +
"1111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111111111111 \n" +
"111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111 \n" +
"1111111111¶¶¶¶¶¶¶¶11¶¶¶¶¶¶1111¶¶¶¶¶¶¶¶¶¶¶¶¶11 \n" +
"1111111¶¶¶¶¶¶¶¶¶¶1¶11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1 \n" +
"1¶¶¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111¶¶¶¶1 \n" +
"111¶¶¶¶¶¶¶¶¶¶¶11¶¶¶¶11¶¶¶¶¶¶¶¶¶¶111111111¶111 \n" +
"11111111¶¶¶¶¶11¶¶¶¶¶¶11¶¶¶¶¶¶¶¶¶¶¶11111111111 \n" +
"1111111¶¶¶¶¶11¶¶¶¶¶¶¶¶11¶¶¶¶¶¶1¶¶¶¶1111111111 \n" +
"111111¶¶¶¶¶11¶¶¶¶¶¶¶¶¶111¶¶¶¶¶111¶¶¶¶¶¶¶¶¶111 \n" +
"11111¶¶¶¶¶¶1¶¶¶¶¶¶¶¶¶11111¶¶¶1111111¶¶¶11¶¶11 \n" +
"11111¶¶¶¶¶11¶¶¶¶¶¶¶¶¶111111¶¶¶111111111111111 \n" +
"1111¶¶¶¶¶¶11¶¶¶¶¶¶¶¶111111¶¶¶¶¶¶¶¶11111111111 \n" +
"111¶¶¶¶¶¶¶11¶¶¶¶¶¶¶¶111111¶¶¶¶¶¶1111111111111 \n" +
"1¶¶¶11¶¶¶¶11¶¶¶¶¶¶¶¶¶111111111111111111111111 \n" +
"111111¶¶¶¶¶1¶¶¶¶¶¶¶¶¶¶11111111111111111111111 \n" +
"111111¶¶¶¶¶1¶¶¶¶¶¶¶¶¶¶¶¶1111111111111¶1111111 \n" +
"111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111111111¶111111 \n" +
"111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111111¶¶11111 \n" +
"11111¶¶¶¶11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶111¶¶¶¶1111 \n" +
"11111¶¶¶1111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶1111 \n" +
"1111¶¶111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶¶1111 \n" +
"11¶¶111111111¶¶¶1111¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶¶¶1111 \n" +
"1111111111111¶¶¶1111111¶¶¶¶¶¶¶¶11¶¶¶¶¶¶¶¶1111 \n" +
"1111111111111¶¶¶111111111¶¶¶¶¶¶11¶¶¶¶¶¶¶¶1111 \n" +
"1111111111111¶¶111111111111¶¶¶¶11¶¶¶¶¶¶¶¶1111 \n" +
"111111111111¶¶1111111111111¶¶¶¶11¶¶¶¶¶11¶1111 \n" +
"111111111111111111111111111¶¶¶¶11¶¶¶¶11111111 \n" +
"111111111111111111111111111¶¶¶¶11¶¶111¶¶11111 \n" +
"111111111111111111111111111¶¶¶¶1¶¶11¶¶¶¶¶1111 \n" +
"11111111111111111111111111¶¶¶¶11111¶¶¶¶¶11111 \n" +
"11111111111111111111111111¶¶¶1111¶¶¶¶¶1111111 \n" +
"1111111111111111111111111¶¶¶111¶¶¶¶¶¶11111111 \n" +
"11111111111111111111111¶¶¶¶11¶¶¶¶¶¶1111111111 \n" +
"1111111111111111111111¶¶¶¶11¶¶¶¶¶111111111111 \n" +
"11111111111111111111¶¶¶¶11¶¶¶¶¶11111111111111 \n" +
"1111111111111111111¶¶¶¶11¶¶¶¶¶111111111111111 \n" +
"111111111111111111¶¶¶¶11¶¶¶¶11111111111111111 \n" +
"11111111111111111¶¶¶¶¶1¶¶¶¶¶11111111111111111 \n" +
"11111111111111111¶¶¶¶11¶¶¶¶111111111111111111 \n" +
"11111111111111111¶¶¶¶11¶¶¶¶1111111¶1111111111 \n" +
"11111111111111111¶¶¶¶¶11¶¶¶¶111111¶¶111111111 \n" +
"111111111111111111¶¶¶¶¶11¶¶¶¶1111¶¶¶111111111 \n" +
"1111111111111111111¶¶¶¶¶11111111¶¶¶¶111111111 \n" +
"111111111111111111111¶¶¶¶¶¶¶¶¶1¶¶¶¶¶¶11111111 \n" +
"11111111111111111111111¶¶¶¶¶¶11¶¶¶¶¶111111111 \n" +
"1111111111111111111111111¶¶¶¶1¶¶¶¶¶¶111111111 \n" +
"11111111111111111111111111¶¶¶11¶¶¶¶¶111111111 \n" +
"11111111111111111111111111¶¶¶11¶¶¶1¶111111111 \n" +
"111111111111111111111111111¶¶1¶¶1111111111111 \n" +
"11111111111111111111111111¶¶¶111¶¶11111111111 \n" +
"11111111111111111111111111¶¶11¶¶¶111111111111 \n" +
"111111111111111111111111¶¶¶11¶¶¶1111111111111 \n" +
"1111111111111111111111¶¶¶¶11¶¶¶11111111111111 \n" +
"111111111111111111111¶¶¶11¶¶¶¶111111111111111 \n" +
"11111111111111111111¶¶¶11¶¶¶11111111111111111 \n" +
"11111111111111111111¶¶¶1¶¶¶111111111111111111 \n" +
"1111111111111111111¶¶¶11¶¶¶111111111111111111 \n" +
"1111111111111111111¶¶¶¶1¶¶¶11111¶111111111111 \n" +
"11111111111111111111¶¶¶¶11¶1111¶¶111111111111 \n" +
"111111111111111111111¶¶¶¶¶¶¶¶¶¶¶¶111111111111 \n" +
"11111111111111111111111¶¶¶¶¶¶¶¶¶¶111111111111 \n" +
"1111111111111111111111111¶¶¶¶¶¶¶1111111111111 \n" +
"1111111111111111111111111¶¶¶¶¶¶¶1111111111111 \n" +
"1111111111111111111111111¶¶¶¶¶¶11111111111111 \n" +
"1111111111111111111111111¶¶¶¶¶111111111111111 \n" +
"1111111111111111111111111¶¶¶¶1111111111111111 \n" +
"111111111111111111111111¶¶¶¶11111111111111111 \n" +
"11111111111111111111111¶¶¶1111111111111111111 \n" +
"1111111111111111111111¶¶111111111111111111111 \n" +
"11111111111111111111¶¶11111111111111111111111\n");
            texto.append("""
                         O NÃO VOCÊ FOI CONSUMIDO PELO FOGO DO DRAGÃO QUE 
                         MORAVA NO VULCÃO !!
                         """);
        }
        if(pontos == 10){
            texto.append("\n_________________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶__________________\n" +
"_____________¶¶¶________________¶¶¶_______________\n" +
"___________¶¶______________________¶¶¶¶___________\n" +
"_________¶¶¶__________________________¶¶¶_________\n" +
"_______¶¶¶___________________¶¶¶¶_______¶¶________\n" +
"_¶¶¶¶¶¶__¶¶¶¶¶¶¶¶¶¶¶¶¶_____¶¶¶__¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶__\n" +
"__¶¶¶¶____¶¶¶¶¶¶¶¶¶_¶¶¶¶¶¶¶¶¶____¶¶¶¶¶¶¶¶¶¶¶¶¶¶___\n" +
"___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶____¶¶¶____\n" +
"__¶___¶¶¶¶¶¶¶¶______¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶______¶¶__¶__\n" +
"_¶¶___¶¶¶¶¶¶¶¶¶______¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______¶¶__¶¶__\n" +
"¶______¶¶¶¶¶¶¶¶_____¶¶¶___¶¶¶¶¶¶¶¶¶___¶¶¶¶¶____¶__\n" +
"¶__________¶¶¶¶¶¶¶¶¶¶¶______¶¶¶¶¶¶¶¶¶¶¶__¶______¶¶\n" +
"¶_______________________________________________¶¶\n" +
"¶________¶¶_____________________________________¶¶\n" +
"¶______¶¶¶¶_________________________¶¶¶¶________¶¶\n" +
"¶_____¶__¶¶_________________________¶¶¶¶________¶¶\n" +
"¶_________¶¶¶______________________¶¶___________¶¶\n" +
"¶___________¶¶¶__________________¶¶¶____________¶¶\n" +
"¶¶____________¶¶¶¶____________¶¶¶¶_____________¶__\n" +
"_¶¶______________¶¶¶¶¶¶¶¶¶¶¶¶¶¶________________¶__\n" +
"__¶___________________________________________¶¶__\n" +
"___¶¶________________________________________¶¶___\n" +
"____¶¶______________________________________¶¶____\n" +
"_____¶¶___________________________________¶¶______\n" +
"_______¶¶_______________________________¶¶¶_______\n" +
"_________¶¶___________________________¶¶¶_________\n" +
"__________¶¶¶¶_____________________¶¶_____________\n" +
"______________¶¶¶¶_____________¶¶¶¶¶______________\n" +
"___________________¶¶¶¶¶¶¶¶¶¶¶¶___________________\n");
            texto.append("""
                         VOCÊ FOI PARA A TERRA DE NOR 
                           SE ALIANDO AS TROPAS DE RESISTÊNCIA 
                           CONTRA A TIRANIA DO REI VEMPTOR ...
                              A ALIANÇA VENCEU E VC FOI COROADO REI DE NOR !!!
                         """);
        }
        
    }
    public void inicio(){
       
       
       
        texto.setText(" █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█\n" +
"█---╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗--█\n" +
"█---║║║╠─║─║─║║║║║╠─--█\n" +
"█---╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝--█\n" +
"█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n" +
"");
        
        
        
        texto.append("..........\n");

        texto.append("            .............\n");
       
        texto.append("                                 .............\n");
        texto.append("""
                     Terra de Nor 2000 anos depois da Era de Vemptor ......
                       O livro do tempo repousava sobre 
                         a proteção da árvore sagrada ,
                            quando suas páginas correram em direção
                     as planícies do sul ....\n""");
        texto.append("""
                     2020 do tempo comum .... 
                     O despertador toca 
                      Acordar ?\n""");
        
        
        
        
        
              
        
        }

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Livro().setVisible(true);
                    System.out.println("teste");
                } catch (InterruptedException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton enviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ler;
    public javax.swing.JButton nao;
    public javax.swing.JButton reiniciar;
    public javax.swing.JButton responder;
    public javax.swing.JButton sim;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
